import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from '../src/components/ResponsiveAppBar'
import Skeleton from '../src/components/Skeleton'
import Paginate from '../src/components/Paginate'
const Home: NextPage = () => {
  return (
    <div className='flex items-center justify-center flex-col'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar />
      <Skeleton/>
      <Paginate/>
    </div>
  )
}

export default Home
